-- ***These are all good***


-- Core Workout list:

-- Treadmill
-- Burpees
-- Jumping_Jacks
-- High_Knees
-- Butt_Kicks
-- Jump_Rope
-- Side_Shuffle
-- Basketball_Shots


-- Treadmill
INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Treadmill',
                      'cardio',
                      Null,
                      Null,
                      Null,
                      '3.5 MPH',
                      720,
                      Null,

                      Null,
                      Null,
                      Null,
                      '4 MPH',
                      720,
                      Null,

                      Null,
                      Null,
                      Null,
                      '5 MPH',
                      720,
                      Null,

                      Null,
                      Null,
                      Null,
                      '6 MPH',
                      720,
                      Null,
                      'Keep pace for 10 minutes. Change Incline settings at your own discretion.',
                      'static/images/workouts/Treadmill.png'
);

-- Burpees
INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Burpees',
                      'cardio',
                      5,
                      3,
                      Null,
                      Null,
                      600,
                      180,

                      8,
                      3,
                      Null,
                      Null,
                      600,
                      120,

                      12,
                      3,
                      Null,
                      Null,
                      600,
                      90,

                      15,
                      3,
                      Null,
                      Null,
                      600,
                      60,
                      'Stand with your feet shoulder-width apart. Push your hips back, bend your knees, and lower your body into a squat. Reach out and fall into push up position.',
                      'static/images/workouts/Burpees.png'
);

-- Jumping_Jacks
INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Jumping Jacks',
                      'cardio',
                      20,
                      3,
                      Null,
                      Null,
                      600,
                      180,

                      40,
                      3,
                      Null,
                      Null,
                      600,
                      120,

                      50,
                      3,
                      Null,
                      Null,
                      600,
                      90,

                      60,
                      3,
                      Null,
                      Null,
                      600,
                      60,
                      'Jumping jack info',
                      'static/images/workouts/Jumping_Jacks.png'
);


-- High_Knees
INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('High Knees',
                      'cardio',
                      20,
                      3,
                      Null,
                      Null,
                      600,
                      180,

                      40,
                      3,
                      Null,
                      Null,
                      600,
                      120,

                      50,
                      3,
                      Null,
                      Null,
                      600,
                      90,

                      60,
                      3,
                      Null,
                      Null,
                      600,
                      60,
                      'High Knees info value',
                      'static/images/workoutsHigh_Knees.png'
);


-- Butt_Kicks
INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Butt Kicks',
                      'cardio',
                      20,
                      3,
                      Null,
                      Null,
                      720,
                      180,

                      40,
                      3,
                      Null,
                      Null,
                      600,
                      120,

                      50,
                      3,
                      Null,
                      Null,
                      420,
                      90,

                      60,
                      3,
                      Null,
                      Null,
                      420,
                      60,
                      'Butt Kicks info value',
                      'static/images/workouts/Butt_Kicks.png'
);

-- Jump_Rope
INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Jump Rope',
                      'cardio',
                      Null,
                      Null,
                      Null,
                      Null,
                      360,
                      Null,

                      Null,
                      Null,
                      Null,
                      Null,
                      360,
                      Null,

                      Null,
                      Null,
                      Null,
                      Null,
                      480,
                      Null,

                      Null,
                      Null,
                      Null,
                      Null,
                      600,
                      Null,
                      'Keep a steady Jump Rope pace for the most of the time in the time limit. Reset timer if you run out of time',
                      'static/images/workouts/Jump_Rope.png'
);

-- Side_Shuffle
INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Side Shuffle',
                      'cardio',
                      5,
                      3,
                      Null,
                      Null,
                      600,
                      Null,

                      10,
                      3,
                      Null,
                      Null,
                      600,
                      Null,

                      15,
                      3,
                      Null,
                      Null,
                      600,
                      Null,

                      20,
                      3,
                      Null,
                      Null,
                      600,
                      Null,
                      'Keep a steady pace that you feel comfortable with, and shuffle 5 yards back and forth for the amount of reps.',
                      'static/images/workouts/Side_Shuffle.png'
);

-- Basketball_Shots
INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Basketball Shots',
                      'cardio',
                      10,
                      3,
                      Null,
                      Null,
                      600,
                      180,

                      20,
                      3,
                      Null,
                      Null,
                      720,
                      180,

                      25,
                      3,
                      Null,
                      Null,
                      780,
                      210,

                      30,
                      3,
                      Null,
                      Null,
                      780,
                      210,
                      'Basketball_Shots info',
                      'static/images/workouts/Basketball_Shots.png'
);



-- Treadmill (duplicated for some reason so I commneted it out just incase we need it)
-- INSERT INTO Workouts(workout_name,
--                      category,
--                      beginner_reps,
--                      beginner_sets,
--                      beginner_weight,
--                      beginner_pace,
--                      beginner_time_limit,
--                      beginner_rest_period,
--                      novice_reps,
--                      novice_sets,
--                      novice_weight,
--                      novice_pace,
--                      novice_time_limit,
--                      novice_rest_period,
--                      intermediate_reps,
--                      intermediate_sets,
--                      intermediate_weight,
--                      intermediate_pace,
--                      intermediate_time_limit,
--                      intermediate_rest_period,
--                      experienced_reps,
--                      experienced_sets,
--                      experienced_weight,
--                      experienced_pace,
--                      experienced_time_limit,
--                      experienced_rest_period,
--                      info,
--                      video_file_name,
--                      created) VALUES
--                      ('Treadmill',
--                       'cardio',
--                       Null,
--                       Null,
--                       Null,
--                       '3.5 MPH',
--                       720,
--                       Null,
--
--                       Null,
--                       Null,
--                       Null,
--                       '4 MPH',
--                       720,
--                       Null,
--
--                       Null,
--                       Null,
--                       Null,
--                       '5 MPH',
--                       720,
--                       Null,
--
--                       Null,
--                       Null,
--                       Null,
--                       '6 MPH',
--                       720,
--                       Null,
--                       'Keep pace for 10 minutes. Change Incline settings at your own discretion.',
--                       'static/images/workouts/Treadmill.png'
-- );
