INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Treadmill',
                      'cardio',
                      Null,
                      Null,
                      Null,
                      2,
                      240,
                      Null,

                      Null,
                      Null,
                      Null,
                      4,
                      360,
                      Null,

                      Null,
                      Null,
                      Null,
                      5,
                      480,
                      Null,

                      Null,
                      Null,
                      Null,
                      6,
                      480,
                      Null,
                      'Treadmill info value',
                      'static/video/treadmill.png'
);



INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Burpees',
                      'cardio',
                      5,
                      3,
                      Null,
                      Null,
                      720,
                      180,

                      8,
                      3,
                      Null,
                      Null,
                      600,
                      120,

                      12,
                      3,
                      Null,
                      Null,
                      420,
                      90,

                      15,
                      3,
                      Null,
                      Null,
                      420,
                      60,
                      'Burpees info value',
                      'static/video/burpees.png'
);


INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Jumping Jacks',
                      'cardio',
                      20,
                      3,
                      Null,
                      Null,
                      720,
                      180,

                      40,
                      3,
                      Null,
                      Null,
                      600,
                      120,

                      50,
                      3,
                      Null,
                      Null,
                      420,
                      90,

                      60,
                      3,
                      Null,
                      Null,
                      420,
                      60,
                      'Jumping Jacks info value',
                      'static/video/jumping-jacks.png'
);


INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('High Knees',
                      'cardio',
                      20,
                      3,
                      Null,
                      Null,
                      720,
                      180,

                      40,
                      3,
                      Null,
                      Null,
                      600,
                      120,

                      50,
                      3,
                      Null,
                      Null,
                      420,
                      90,

                      60,
                      3,
                      Null,
                      Null,
                      420,
                      60,
                      'High Knees info value',
                      'static/video/high-knees.png'
);


INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Butt Kicks',
                      'cardio',
                      20,
                      3,
                      Null,
                      Null,
                      720,
                      180,

                      40,
                      3,
                      Null,
                      Null,
                      600,
                      120,

                      50,
                      3,
                      Null,
                      Null,
                      420,
                      90,

                      60,
                      3,
                      Null,
                      Null,
                      420,
                      60,
                      'Butt Kicks info value',
                      'static/video/butt-kicks.png'
);




INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Jumprope',
                      'cardio',
                      Null,
                      Null,
                      Null,
                      2,
                      240,
                      60,

                      Null,
                      Null,
                      Null,
                      4,
                      360,
                      60,

                      Null,
                      Null,
                      Null,
                      5,
                      480,
                      60,

                      Null,
                      Null,
                      Null,
                      6,
                      480,
                      60,
                      'Jumprope info value',
                      'static/video/jumpropepng'
);




