-- *** These are all good ***


-- Chest Workouts list:

-- Push_Ups
-- Decline_Push_Ups
-- Incline_Push-Ups
-- Bench_Press
-- Flys
-- Dips
-- Incline_Bench_Press
-- Decline_Bench_Press
-- Plate_Squeeze
-- Bench_Pull_Over


-- Push_Ups
INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Push Ups',
                      'chest',
                      5,
                      3,
                      Null,
                      Null,
                      720,
                      180,

                      10,
                      3,
                      Null,
                      Null,
                      600,
                      120,

                      20,
                      3,
                      Null,
                      Null,
                      420,
                      90,

                      30,
                      3,
                      Null,
                      Null,
                      420,
                      60,
                      'Push Up info value',
                      'static/images/workouts/Push_Ups.png'
);


-- Decline_Push_Ups
INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Decline Push Ups',
                      'chest',
                      5,
                      3,
                      Null,
                      Null,
                      720,
                      180,

                      10,
                      3,
                      Null,
                      Null,
                      600,
                      120,

                      20,
                      3,
                      Null,
                      Null,
                      420,
                      90,

                      30,
                      3,
                      Null,
                      Null,
                      420,
                      60,
                      'Decline Push Up info value',
                      'static/images/workouts/Decline_Push_Ups.png'
);

-- Incline_Push_Ups
INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Incline Push Ups',
                      'chest',
                      5,
                      3,
                      Null,
                      Null,
                      720,
                      180,

                      10,
                      3,
                      Null,
                      Null,
                      600,
                      120,

                      20,
                      3,
                      Null,
                      Null,
                      420,
                      90,

                      30,
                      3,
                      Null,
                      Null,
                      420,
                      60,
                      'Incline Push Up info value',
                      'static/images/workouts/Incline_Push_Ups.png'
);


-- Bench_Press
INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Bench Press',
                      'chest',
                      8,
                      3,
                      '20 Lbs Dumbbells',
                      Null,
                      720,
                      180,

                      10,
                      3,
                      '25 Lbs Dumbbells',
                      Null,
                      600,
                      120,

                      12,
                      3,
                      '30 Lbs Dumbbells'
                      Null,
                      600,
                      90,

                      12,
                      3,
                      '40 Lbs Dumbbells'
                      Null,
                      600,
                      60,
                      'Bench Press info value',
                      'static/images/workouts/Bench_Press.png'
);



-- Flys
INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Flys',
                      'chest',
                      5,
                      3,
                      '10 Lbs Dumbbells',
                      Null,
                      600,
                      180,

                      8,
                      3,
                      '15 Lbs Dumbbells',
                      Null,
                      600,
                      120,

                      10,
                      3,
                      '20 Lbs Dumbbells',
                      Null,
                      600,
                      90,

                      12,
                      3,
                      '30 Lbs Dumbbells',
                      Null,
                      420,
                      60,
                      'Dumbbell Flys info value',
                      'static/images/workouts/Flys.png'
);

-- Dips
INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Dips',
                      'chest',
                      3,
                      3,
                      Null,
                      Null,
                      600,
                      180,

                      6,
                      3,
                      Null,
                      Null,
                      600,
                      120,

                      10,
                      3,
                      Null,
                      Null,
                      600,
                      90,

                      12,
                      3,
                      Null,
                      Null,
                      600,
                      60,
                      'Dips info value',
                      'static/images/workouts/Dips.png'
);


-- Incline_Bench_Press
INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Incline Bench Press',
                      'chest',
                      8,
                      3,
                      '15 Lbs Dumbbells',
                      Null,
                      720,
                      180,

                      10,
                      3,
                      '20 Lbs Dumbbells',
                      Null,
                      600,
                      120,

                      12,
                      3,
                      '25 Lbs Dumbbells',
                      Null,
                      600,
                      90,

                      15,
                      3,
                      '30 Lbs Dumbbells',
                      Null,
                      600,
                      60,
                      'Incline Bench Press info value',
                      'static/images/workouts/Incline_Bench_Press.png'
);

-- Decline_Bench_Press
INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Decline Bench Press',
                      'chest',
                      8,
                      3,
                      '15 Lbs Dumbbells',
                      Null,
                      720,
                      180,

                      10,
                      3,
                      '20 Lbs Dumbbells',
                      Null,
                      600,
                      120,

                      12,
                      3,
                      '25 Lbs Dumbbells',
                      Null,
                      600,
                      90,

                      15,
                      3,
                      '30 Lbs Dumbbells',
                      Null,
                      600,
                      60,
                      'Incline Bench Press info value',
                      'static/images/workouts/Decline_Bench_Press.png'
);


-- Plate_Squeeze
INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Plate Squeeze',
                      'chest',
                      10,
                      3,
                      '5 Lbs',
                      Null,
                      600,
                      180,

                      8,
                      3,
                      '10 Lbs',
                      Null,
                      600,
                      120,

                      8,
                      3,
                      '15 Lbs',
                      Null,
                      600,
                      90,

                      8,
                      3,
                      '20 Lbs',
                      Null,
                      600,
                      60,
                      'Plate Squeeze info value',
                      'static/images/workouts/Plate_Squeeze.png'
);

-- Bench_Pull_Over
INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Bench Pull Over',
                      'chest',
                      5,
                      3,
                      '10 Lbs (x1 Dumbbell)',
                      Null,
                      600,
                      180,

                      8,
                      3,
                      '15 Lbs (x1 Dumbbell)',
                      Null,
                      600,
                      120,

                      8,
                      3,
                      '20 Lbs (x1 Dumbbell)',
                      Null,
                      600,
                      90,

                      10,
                      3,
                      '30 Lbs (x1 Dumbbell)',
                      Null,
                      600,
                      60,
                      'Bench Pull Over info value',
                      'static/images/workouts/Bench_Pull_Over.png'
);
