-- workout: Push Ups
INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Push Ups',
                      'chest',
                      5,
                      3,
                      Null,
                      Null,
                      720,
                      180,

                      10,
                      3,
                      Null,
                      Null,
                      600,
                      120,

                      20,
                      3,
                      Null,
                      Null,
                      420,
                      90,

                      30,
                      3,
                      Null,
                      Null,
                      420,
                      60,
                      'Push Up info value',
                      'static/video/push-ups.png'
);

INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Bench Press',
                      'chest',
                      7,
                      3,
                      50,
                      Null,
                      720,
                      180,

                      10,
                      3,
                      75,
                      Null,
                      600,
                      120,

                      12,
                      3,
                      100,
                      Null,
                      420,
                      90,

                      15,
                      3,
                      125,
                      Null,
                      420,
                      60,
                      'Bench Press info value',
                      'static/video/bench-press.png'
);


INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Dumbbell Flys',
                      'chest',
                      5,
                      3,
                      10,
                      Null,
                      720,
                      180,

                      8,
                      3,
                      15,
                      Null,
                      600,
                      120,

                      10,
                      3,
                      20,
                      Null,
                      420,
                      90,

                      12,
                      3,
                      25,
                      Null,
                      420,
                      60,
                      'Dumbbell Flys info value',
                      'static/video/dumbbell-flys.png'
);

INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Dips',
                      'chest',
                      3,
                      3,
                      Null,
                      Null,
                      720,
                      180,

                      6,
                      3,
                      Null,
                      Null,
                      600,
                      120,

                      10,
                      3,
                      Null,
                      Null,
                      420,
                      90,

                      12,
                      3,
                      Null,
                      Null,
                      420,
                      60,
                      'Dips info value',
                      'static/video/dips.png'
);

INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Incline Bench Press',
                      'chest',
                      5,
                      3,
                      25,
                      Null,
                      720,
                      180,

                      10,
                      3,
                      50,
                      Null,
                      600,
                      120,

                      12,
                      3,
                      75,
                      Null,
                      420,
                      90,

                      15,
                      3,
                      100,
                      Null,
                      420,
                      60,
                      'Incline Bench Press info value',
                      'static/video/incline-bench-press.png'
);

INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Decline Bench Press',
                      'chest',
                      7,
                      3,
                      25,
                      Null,
                      720,
                      180,

                      10,
                      3,
                      50,
                      Null,
                      600,
                      120,

                      12,
                      3,
                      75,
                      Null,
                      420,
                      90,

                      15,
                      3,
                      100,
                      Null,
                      420,
                      60,
                      'Push Up info value',
                      'static/video/push-ups.png'
);



INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Seated Machine Chest Press',
                      'chest',
                      5,
                      3,
                      50,
                      Null,
                      720,
                      180,

                      7,
                      3,
                      75,
                      Null,
                      600,
                      120,

                      10,
                      3,
                      100,
                      Null,
                      420,
                      90,

                      12,
                      3,
                      125,
                      Null,
                      420,
                      60,
                      'Push Up info value',
                      'static/video/push-ups.png'
);


INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Pec-Deck Machine',
                      'chest',
                      5,
                      3,
                      20,
                      Null,
                      720,
                      180,

                      7,
                      3,
                      40,
                      Null,
                      600,
                      120,

                      10,
                      3,
                      60,
                      Null,
                      420,
                      90,

                      12,
                      3,
                      80,
                      Null,
                      420,
                      60,
                      'Push Up info value',
                      'static/video/push-ups.png'
);






