INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Sit Ups',
                      'core',
                      10,
                      3,
                      Null,
                      Null,
                      720,
                      180,

                      15,
                      3,
                      Null,
                      Null,
                      600,
                      120,

                      20,
                      3,
                      Null,
                      Null,
                      420,
                      90,

                      30,
                      3,
                      Null,
                      Null,
                      420,
                      60,
                      'Sit Ups info value',
                      'static/video/sit-ups.png'
);


INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Plank',
                      'core',
                      Null,
                      3,
                      Null,
                      20,
                      Null,
                      180,

                      Null,
                      3,
                      Null,
                      30,
                      Null,
                      120,

                      Null,
                      3,
                      Null,
                      45,
                      Null,
                      90,

                      Null,
                      3,
                      Null,
                      60,
                      Null,
                      60,
                      'Plank info value',
                      'static/video/plank.png'
);



INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Mountain Climbers',
                      'core',
                      10,
                      3,
                      Null,
                      Null,
                      720,
                      180,

                      20,
                      3,
                      Null,
                      Null,
                      600,
                      120,

                      40,
                      3,
                      Null,
                      Null,
                      420,
                      90,

                      60,
                      3,
                      Null,
                      Null,
                      420,
                      60,
                      'Mountain Climbers value',
                      'static/video/mountain-climbers.png'
);



INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Russian Twists',
                      'core',
                      6,
                      3,
                      5,
                      Null,
                      720,
                      180,

                      10,
                      3,
                      5,
                      Null,
                      600,
                      120,

                      15,
                      3,
                      10,
                      Null,
                      420,
                      90,

                      20,
                      3,
                      15,
                      Null,
                      420,
                      60,
                      'Russian Twists info value',
                      'static/video/russian-twists.png'
);



INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Leg Raises',
                      'core',
                      5,
                      3,
                      Null,
                      Null,
                      720,
                      180,

                      10,
                      3,
                      Null,
                      Null,
                      600,
                      120,

                      15,
                      3,
                      Null,
                      Null,
                      420,
                      90,

                      20,
                      3,
                      Null,
                      Null,
                      420,
                      60,
                      'Leg Raises value',
                      'static/video/leg-raises.png'
);



INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Machine Crunches',
                      'core',
                      5,
                      3,
                      5,
                      Null,
                      720,
                      180,

                      10,
                      3,
                      10,
                      Null,
                      600,
                      120,

                      15,
                      3,
                      15,
                      Null,
                      420,
                      90,

                      20,
                      3,
                      20,
                      Null,
                      420,
                      60,
                      'Machine Crunches value',
                      'static/video/machine-crunches.png'
);



INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Hyperextensions',
                      'core',
                      5,
                      3,
                      Null,
                      Null,
                      720,
                      180,

                      10,
                      3,
                      Null,
                      Null,
                      600,
                      120,

                      15,
                      3,
                      Null,
                      Null,
                      420,
                      90,

                      20,
                      3,
                      Null,
                      Null,
                      420,
                      60,
                      'Hyperextensions value',
                      'static/video/hyperextensions.png'
);