use tempdb1;
SET FOREIGN_KEY_CHECKS=0;
drop table IF EXISTS Accounts;
SET FOREIGN_KEY_CHECKS=1;
CREATE TABLE Accounts (account_id INT NOT NULL UNIQUE AUTO_INCREMENT,
                      username VARCHAR(25) NOT NULL,
                      email VARCHAR(50) NOT NULL UNIQUE,
                      password VARCHAR(60) NOT NULL,
                      logged_in BOOLEAN NOT NULL,
                      age TINYINT NOT NULL check(age > 13 and age < 65),
                      height_in TINYINT NOT NULL CHECK(height_in >= 0 and height_in < 12),
                      height_ft TINYINT NOT NULL CHECK(height_ft >= 3 and height_ft <= 8),
                      gender VARCHAR(6) NOT NULL CHECK(gender IN ('male', 'female')),
                      timezone VARCHAR(36) NOT NULL CHECK(timezone IN ('America/New_York', 'America/Merida', 'America/Boise', 'America/Dawson', 'America/Anchorage', 'Pacific/Honolulu', 'America/Phoenix')),
                      exp_cardio VARCHAR(12) NOT NULL CHECK(exp_cardio IN ('beginner', 'novice', 'intermediate', 'experienced')),
                      exp_chest VARCHAR(12) NOT NULL CHECK(exp_chest IN ('beginner', 'novice', 'intermediate', 'experienced')),
                      exp_legs VARCHAR(12) NOT NULL CHECK(exp_legs IN ('beginner', 'novice', 'intermediate', 'experienced')),
                      exp_back VARCHAR(12) NOT NULL CHECK(exp_back IN ('beginner', 'novice', 'intermediate', 'experienced')),
                      exp_core VARCHAR(12) NOT NULL CHECK(exp_core IN ('beginner', 'novice', 'intermediate', 'experienced')),
                      exp_shoulders VARCHAR(12) NOT NULL CHECK(exp_shoulders IN ('beginner', 'novice', 'intermediate', 'experienced')),
                      exp_arms VARCHAR(12) NOT NULL CHECK(exp_arms IN ('beginner', 'novice', 'intermediate', 'experienced')),
                      password_change_code INT UNIQUE CHECK(password_change_code <= 10000000 and password_change_code >= 99999999),
                      created DECIMAL(16,6) NOT NULL,
                      last_activity DECIMAL(16,6) NOT NULL,
                      PRIMARY KEY(account_id)) ENGINE=INNODB;

INSERT INTO Accounts (username,
                      email,
                      password,
                      logged_in,
                      age,
                      height_in,
                      height_ft,
                      gender,
                      timezone,
                      exp_cardio,
                      exp_chest,
                      exp_legs,
                      exp_back,
                      exp_core,
                      exp_shoulders,
                      exp_arms,
                      created,
                      last_activity) VALUES
                     ('mac',
                      'mac_cassidy@ymail.com',
                      '$2b$12$KwrYAhmoaHzexKqFExP.wuGbOwqxfziRCOijBqqRm3PA05E1.QLhm',
                      FALSE,
                      24,
                      7,
                      5,
                      'male',
                      'America/New_York',
                      'beginner',
                      'beginner',
                      'beginner',
                      'beginner',
                      'beginner',
                      'beginner',
                      'beginner',
                      1585211987.176413,
                      1585411905.674891
                      );
INSERT INTO Accounts (username,
                      email,
                      password,
                      logged_in,
                      age,
                      height_in,
                      height_ft,
                      gender,
                      timezone,
                      exp_cardio,
                      exp_chest,
                      exp_legs,
                      exp_back,
                      exp_core,
                      exp_shoulders,
                      exp_arms,
                      created,
                      last_activity) VALUES
                      ('evan',
                       'jonnyapple1001@gmail.com',
                       '$2b$12$QUFP2gB.N1y0RDLt.qD.8.VPJqyOIwV1zXpGtkcCo7TOldJnUD5n6',
                       False,
                       22,
                       9,
                       5,
                       'male',
                       'America/New_York',
                       'novice',
                       'novice',
                       'novice',
                       'novice',
                       'novice',
                       'novice',
                       'novice',
                       1585311977.176413,
                       1585419905.674891
                      );
