INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Squats',
                      'legs',
                      5,
                      3,
                      45,
                      Null,
                      720,
                      180,

                      7,
                      3,
                      65,
                      Null,
                      600,
                      120,

                      10,
                      3,
                      95,
                      Null,
                      420,
                      90,

                      12,
                      3,
                      135,
                      Null,
                      420,
                      60,
                      'Squats info value',
                      'static/video/squats.png'
);



INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Dumbbell Step Up',
                      'legs',
                      5,
                      3,
                      10,
                      Null,
                      720,
                      180,

                      7,
                      3,
                      20,
                      Null,
                      600,
                      120,

                      10,
                      3,
                      30,
                      Null,
                      420,
                      90,

                      12,
                      3,
                      50,
                      Null,
                      420,
                      60,
                      'Dumbbell Step Up info value',
                      'static/video/dumbbell-step-up.png'
);



INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Machine Leg Press',
                      'legs',
                      5,
                      3,
                      40,
                      Null,
                      720,
                      180,

                      7,
                      3,
                      80,
                      Null,
                      600,
                      120,

                      10,
                      3,
                      100,
                      Null,
                      420,
                      90,

                      12,
                      3,
                      150,
                      Null,
                      420,
                      60,
                      'Shoulder Dumbbell Press info value',
                      'static/video/shoulder-dumbbell-press.png'
);


INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Calf Raises',
                      'legs',
                      10,
                      3,
                      Null,
                      Null,
                      720,
                      180,

                      15,
                      3,
                      Null,
                      Null,
                      600,
                      120,

                      20,
                      3,
                      Null,
                      Null,
                      420,
                      90,

                      30,
                      3,
                      Null,
                      Null,
                      420,
                      60,
                      'Calf Raises value',
                      'static/video/calf-raises.png'
);



INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Dumbbell Lunges',
                      'legs',
                      6,
                      3,
                      10,
                      Null,
                      720,
                      180,

                      8,
                      3,
                      20,
                      Null,
                      600,
                      120,

                      10,
                      3,
                      30,
                      Null,
                      420,
                      90,

                      12,
                      3,
                      40,
                      Null,
                      420,
                      60,
                      'Dumbbell Lunges info value',
                      'static/video/dumbbell-lunges.png'
);

