INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Shoulder Dumbbell Press',
                      'shoulders',
                      5,
                      3,
                      15,
                      Null,
                      720,
                      180,

                      7,
                      3,
                      25,
                      Null,
                      600,
                      120,

                      10,
                      3,
                      35,
                      Null,
                      420,
                      90,

                      12,
                      3,
                      45,
                      Null,
                      420,
                      60,
                      'Shoulder Dumbbell Press info value',
                      'static/video/shoulder-dumbbell-press.png'
);



INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Lateral Raises',
                      'shoulders',
                      5,
                      3,
                      5,
                      Null,
                      720,
                      180,

                      7,
                      3,
                      10,
                      Null,
                      600,
                      120,

                      10,
                      3,
                      12,
                      Null,
                      420,
                      90,

                      12,
                      3,
                      15,
                      Null,
                      420,
                      60,
                      'Lateral Raises info value',
                      'static/video/lateral-raises.png'
);


INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Front Raises',
                      'shoulders',
                      5,
                      3,
                      5,
                      Null,
                      720,
                      180,

                      7,
                      3,
                      10,
                      Null,
                      600,
                      120,

                      10,
                      3,
                      12,
                      Null,
                      420,
                      90,

                      12,
                      3,
                      15,
                      Null,
                      420,
                      60,
                      'Front Raises info value',
                      'static/video/front-raises.png'
);

INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Shrugs',
                      'shoulders',
                      5,
                      3,
                      20,
                      Null,
                      720,
                      180,

                      7,
                      3,
                      25,
                      Null,
                      600,
                      120,

                      10,
                      3,
                      35,
                      Null,
                      420,
                      90,

                      12,
                      3,
                      45,
                      Null,
                      420,
                      60,
                      'Shrugs info value',
                      'static/video/shrugs.png'
);


INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Machine Shoulder Press',
                      'shoulders',
                      5,
                      3,
                      20,
                      Null,
                      720,
                      180,

                      7,
                      3,
                      35,
                      Null,
                      600,
                      120,

                      10,
                      3,
                      45,
                      Null,
                      420,
                      90,

                      12,
                      3,
                      60,
                      Null,
                      420,
                      60,
                      'Machine Shoulder Press info value',
                      'static/video/machine-shoulder-press.png'
);


INSERT INTO Workouts(workout_name,
                     category,
                     beginner_reps,
                     beginner_sets,
                     beginner_weight,
                     beginner_pace,
                     beginner_time_limit,
                     beginner_rest_period,
                     novice_reps,
                     novice_sets,
                     novice_weight,
                     novice_pace,
                     novice_time_limit,
                     novice_rest_period,
                     intermediate_reps,
                     intermediate_sets,
                     intermediate_weight,
                     intermediate_pace,
                     intermediate_time_limit,
                     intermediate_rest_period,
                     experienced_reps,
                     experienced_sets,
                     experienced_weight,
                     experienced_pace,
                     experienced_time_limit,
                     experienced_rest_period,
                     info,
                     video_file_name,
                     created) VALUES
                     ('Seated Barbell Press',
                      'shoulders',
                      5,
                      3,
                      15,
                      Null,
                      720,
                      180,

                      7,
                      3,
                      25,
                      Null,
                      600,
                      120,

                      10,
                      3,
                      35,
                      Null,
                      420,
                      90,

                      12,
                      3,
                      45,
                      Null,
                      420,
                      60,
                      'Seated Barbell Press info value',
                      'static/video/seated-barbell-press.png'
);

                     